### PR TITLE
Fixed project setup and tools

### PR DESCRIPTION
**Pull request by micheledallerive**
Added ESLint and Prettier to have a coherent code style and format.
Corrected the app file linting errors.
Created middlewares and utils folders.

### CODE REVIEW

**Comment by Hwid2121** [comment]
Good job Michele

**Review by JekxDevil — APPROVED** [review]

**Comment by micheledallerive** [comment]
> Good job Michele

Grazie nico, pero sarebbe meglio se invece di commentare me la approvassi :D

**Review by Hwid2121 — APPROVED** [review]
Good job Michele 👍🏿👍🏿👍🏿👍🏿

**Comment by JekxDevil** [comment]
Leave the branch open until M1 presentation, to see if further changes are needed.

**Pull request merged**
